import type { PlayerLabels } from './types'

export const defaultPlayerLabels: PlayerLabels = {
  play: 'Play',
  pause: 'Pause',
  replay: 'Replay',
  mute: 'Mute',
  unmute: 'Unmute',
  settings: 'Settings',
  pip: 'Picture in Picture',
  pipExit: 'Exit Picture in Picture',
  miniPlayer: 'Mini player',
  exitMiniPlayer: 'Exit mini player',
  fullscreen: 'Fullscreen',
  fullscreenExit: 'Exit fullscreen',
  speed: 'Speed',
  quality: 'Quality',
  subtitles: 'Subtitles',
  off: 'Off',
  endedTitle: "You've reached the end",
  screenshot: 'Screenshot',
  flip: 'Flip',
  flipNormal: 'Normal',
  flipHorizontal: 'Horizontal',
  flipVertical: 'Vertical',
  aspectRatio: 'Aspect Ratio',
  aspectRatioDefault: 'Default',
  aspectRatio16: '16 : 9',
  aspectRatio4: '4 : 3',
  aspectRatioFill: 'Fill',
  aspectRatioCover: 'Crop / Cover',
  aspectRatio21: '21 : 9',
  continue: 'Continue',
  continuePlay: 'Continue playing at',
  continueStartOver: 'Start over',
  error: 'An error occurred',
  retry: 'Retry',
  contextMenuPlay: 'Play',
  contextMenuPause: 'Pause',
  contextMenuLoop: 'Loop',
  infoPanel: 'Debug stats',
  loop: 'Loop',
}
