import {
  Check,
  ChevronLeft,
  Loader2,
  Maximize,
  Minimize,
  Pause,
  PictureInPicture2,
  Play,
  RotateCcw,
  Settings2,
  SkipBack,
  SkipForward,
  Volume1,
  Volume2,
  VolumeX,
} from 'lucide-react'
import type { PlayerIcons, PlayerLabels } from './types'

export const defaultPlayerLabels: PlayerLabels = {
  play: 'Play',
  pause: 'Pause',
  replay: 'Replay',
  mute: 'Mute',
  unmute: 'Unmute',
  settings: 'Settings',
  pip: 'Picture in Picture',
  pipExit: 'Exit Picture in Picture',
  fullscreen: 'Fullscreen',
  fullscreenExit: 'Exit fullscreen',
  speed: 'Speed',
  quality: 'Quality',
  subtitles: 'Subtitles',
  off: 'Off',
  endedTitle: "You've reached the end",
}

export const defaultPlayerIcons: PlayerIcons = {
  play: Play,
  pause: Pause,
  replay: RotateCcw,
  skipBack: SkipBack,
  skipForward: SkipForward,
  volumeHigh: Volume2,
  volumeLow: Volume1,
  volumeOff: VolumeX,
  settings: Settings2,
  pip: PictureInPicture2,
  fullscreen: Maximize,
  fullscreenExit: Minimize,
  chevronLeft: ChevronLeft,
  check: Check,
  spinner: Loader2,
}
