export type PlayerSlotName =
  | 'playButton'
  | 'seekBar'
  | 'volumeControl'
  | 'timeDisplay'
  | 'settingsButton'
  | 'settingsMenu'
  | 'fullscreenButton'
  | 'pipButton'
  | 'bufferingOverlay'
  | 'pauseOverlay'
  | 'endOverlay'
